In [36]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from util import *

In [ ]:
df = pd.read_excel('/workspaces/PFDA/System-Data-Qtr-Hourly-November-2024 (1).xlsx')
df.head()

In [ ]:
df.columns

In [ ]:
# Extract the location from the csv files in weather
csv_files = glob.glob('data/weather/*.csv')

location = []

for file in csv_files:
    name = extract_location(file)
    location.append(name)
print(location)

In [ ]:
# Extract the location from the csv files in weather
csv_files = glob.glob('data/weather/*.csv')

location_dict = {}

for file in csv_files:
    name = extract_location(file)
    location_dict[name + '_df'] = file
print(location_dict)

In [ ]:
def load_weather(file_name):
    '''A function to read in a weather csv file.'''
       
    file_path = 'data/weather/'

    for skip_rows in [17, 23]:
        weather_df = pd.read_csv(file_path + file_name,
            skiprows = skip_rows,
            usecols= ['date', 'rain', 'temp', 'msl', 'wdsp', 'wddir'],
            na_values = ' ',
            index_col= 'date', 
            parse_dates= ['date'], 
            date_format = "%d-%b-%Y %H:%M")
            
        weather_df = weather_df['2014': '2024']

    return weather_df

#date, rain,temp,msl,wdsp,wddir

In [ ]:
reg = LinearRegression()

reg.fit(X_train, y_train)
y_predictions = reg.predict(X_test)

# Calculate R-squared, default metric for linear regression, value between 0 and 1
r_squared = reg.score(X_test, y_test)

print(f'R squared: {r_squared}')

# Root Mean squared error, measured in units of target variable squared. 
rmse = root_mean_squared_error(y_test, y_predictions)

print(f'RMSE: {rmse}')

,rain,temp,rhum,msl,wdsp,wddir,rain.1,temp.1,rhum.1,msl.1,...,rhum.10,msl.10,wdsp.10,wddir.10,rain.11,temp.11,rhum.11,msl.11,wdsp.11,wddir.11
date,,,,,,,,,,,,,,,,,,,,,
1944-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.0,1027.9,19,290.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.0,1027.6,19,280.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.0,1027.0,19,260.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90.0,1026.2,19,270.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.0,1025.5,19,270.0,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
full_weather.head()

,rain,temp,rhum,msl,wdsp,wddir,rain,temp,rhum,msl,...,rhum,msl,wdsp,wddir,rain,temp,rhum,msl,wdsp,wddir
date,,,,,,,,,,,,,,,,,,,,,
1944-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93.0,1027.9,19,290.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.0,1027.6,19,280.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.0,1027.0,19,260.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,90.0,1026.2,19,270.0,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,89.0,1025.5,19,270.0,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
full_weather.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 709321 entries, 1944-01-01 00:00:00 to 2024-12-01 00:00:00
Data columns (total 72 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   rain    173192 non-null  float64
 1   temp    173223 non-null  float64
 2   rhum    173231 non-null  float64
 3   msl     173016 non-null  float64
 4   wdsp    173199 non-null  float64
 5   wddir   173149 non-null  float64
 6   rain    147379 non-null  float64
 7   temp    147413 non-null  float64
 8   rhum    147412 non-null  float64
 9   msl     147373 non-null  float64
 10  wdsp    147404 non-null  float64
 11  wddir   147384 non-null  float64
 12  rain    185748 non-null  float64
 13  temp    184573 non-null  float64
 14  rhum    184625 non-null  float64
 15  msl     184745 non-null  float64
 16  wdsp    185772 non-null  float64
 17  wddir   185412 non-null  float64
 18  rain    129395 non-null  float64
 19  temp    129397 non-null  float64
 20  rhum    129385 non-null  float64
 21  msl     129187 non-null  float64
 22  wdsp    129382 non-null  float64
 23  wddir   129382 non-null  float64
 24  rain    177083 non-null  float64
 25  temp    177084 non-null  float64
 26  rhum    177039 non-null  float64
 27  msl     176511 non-null  float64
 28  wdsp    177062 non-null  float64
 29  wddir   176687 non-null  float64
 30  rain    131932 non-null  float64
 31  temp    231691 non-null  float64
 32  rhum    141395 non-null  float64
 33  msl     227224 non-null  float64
 34  wdsp    159623 non-null  float64
 35  wddir   149278 non-null  float64
 36  rain    709278 non-null  float64
 37  temp    709260 non-null  float64
 38  rhum    709260 non-null  float64
 39  msl     709260 non-null  float64
 40  wdsp    709275 non-null  float64
 41  wddir   709211 non-null  float64
 42  rain    597898 non-null  float64
 43  temp    597898 non-null  float64
 44  rhum    597898 non-null  float64
 45  msl     597898 non-null  float64
 46  wdsp    597897 non-null  float64
 47  wddir   597890 non-null  float64
 48  rain    549361 non-null  float64
 49  temp    551520 non-null  float64
 50  rhum    551518 non-null  float64
 51  msl     551520 non-null  float64
 52  wdsp    551520 non-null  float64
 53  wddir   551520 non-null  float64
 54  rain    694704 non-null  float64
 55  temp    694704 non-null  float64
 56  rhum    694704 non-null  float64
 57  msl     694704 non-null  float64
 58  wdsp    694692 non-null  float64
 59  wddir   694692 non-null  float64
 60  rain    709321 non-null  float64
 61  temp    709321 non-null  float64
 62  rhum    709320 non-null  float64
 63  msl     709321 non-null  float64
 64  wdsp    709321 non-null  int64
 65  wddir   709320 non-null  float64
 66  rain    447638 non-null  float64
 67  temp    447640 non-null  float64
 68  rhum    445617 non-null  float64
 69  msl     426857 non-null  float64
 70  wdsp    447590 non-null  float64
 71  wddir   447436 non-null  float64
dtypes: float64(71), int64(1)
memory usage: 395.1 MB

In [ ]:

models = {"Linear Regression": LinearRegression(), "Ridge": Ridge(alpha=0.1), "Lasso": Lasso(alpha=0.1)}
results = []

# Loop through the models' values
for model in models.values():
  kf = KFold(n_splits=6, random_state=241, shuffle=True)
  
  # Perform cross-validation
  cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=kf)
  
  # Append the results
  results.append(cv_scores)

# Create a box plot of the results
plt.boxplot(results, tick_labels=models.keys())
plt.show()

In [ ]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    model.predict(X_test_scaled)
    test_score = model.score(X_test_scaled, y_test)
    print(f'Test set accuracy: {test_score}')

In [ ]:
for name, model in models.items():
  
    # Fit the model to the training data
    model.fit(X_train, y_train)
  
    # Make predictions on the test set
    y_predictions = model.predict(X_test).round(3)
  
    # Calculate the test_rmse
    test_rmse = root_mean_squared_error(y_test, y_predictions).round(3)
    print("{} Test Set RMSE: {}".format(name, test_rmse))

    test_r2 = model.score(X_test, y_test)
    print("{} R_squared:{}".format(name, test_r2))

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {"Linear Regression": LinearRegression(), "Ridge": Ridge(alpha=0.001), "Lasso": Lasso(alpha=0.001)}
results = []

# Loop through the models' values
for model in models.values():
  kf = KFold(n_splits=6, random_state=241, shuffle=True)
  
  # Perform cross-validation
  cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=kf)
  
  # Append the results
  results.append(cv_scores)

# Create a box plot of the results
plt.boxplot(results, tick_labels=models.keys())
plt.show()

In [ ]:
results

In [ ]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    test_score = model.score(X_test_scaled, y_test)
    print(f'Test set accuracy {model}: {test_score}')

In [ ]:
for name, model in models.items():
  
    # Fit the model to the training data
    model.fit(X_train_scaled, y_train)
  
    # Make predictions on the test set
    y_predictions = model.predict(X_test_scaled)
  
    # Calculate the test_rmse
    test_rmse = root_mean_squared_error(y_test, y_predictions)
    print("{} Test Set RMSE: {}".format(name, test_rmse))

    test_r2 = model.score(X_test_scaled, y_test)
    print("{} R_squared:{}".format(name, test_r2))

In [ ]:
print("Predictions: {},\nActual Values: {}".format(y_predictions[:5], y_test[:5]))

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html#sklearn.metrics.r2_score
r2_score(y_test, y_predictions)

In [ ]:
kf = KFold(n_splits= 6, shuffle= True, random_state= 241)
reg = LinearRegression()
cv_results = cross_val_score(reg, X, y, cv = kf)
print(cv_results)
print(f'The mean score is {np.mean(cv_results).round(3)}, with standard deviation of {np.std(cv_results).round(3)}, {np.quantile(cv_results, [0.025, 0.975])}')

In [ ]:
from sklearn.linear_model import Ridge
ridge_scores = []
for alpha in [0.1, 1.0, 10.0, 100.0, 1000.0]:
    ridge = Ridge(alpha= alpha)
    ridge.fit(X_train_scaled, y_train)
    y_predictions = ridge.predict(X_test_scaled)
    ridge_scores.append(ridge.score(X_test_scaled, y_test))

print(ridge_scores)

In [ ]:
from sklearn.linear_model import Lasso

lasso_scores = []
for alpha in [0.1, 1.0, 10.0, 100.0, 1000.0]:
    lasso = Lasso(alpha= alpha)
    lasso.fit(X_train_scaled, y_train)
    y_predictions = lasso.predict(X_test_scaled)
    lasso_scores.append(lasso.score(X_test_scaled, y_test))

print(lasso_scores)

In [ ]:
# Can be used to assess feature importance
fig, ax = plt.subplots(figsize = (8,6))
names = electricity_weather.drop('Wind Energy (MW)', axis= 1).columns

lasso = Lasso(alpha= 0.1)
lasso_coef = lasso.fit(X_train_scaled, y_train).coef_
plt.bar(names, lasso_coef)
plt.xticks(rotation = 45)
plt.show()

In [ ]:
# Hyperparameter tuning

from sklearn.model_selection import GridSearchCV

kf = KFold(n_splits= 5, shuffle= True, random_state = 241)

param_grid = {'alpha': np.arange(0.0001, 1, 10),
              'solver': ['sag', 'lsqr']}

ridge = Ridge()
ridge_cv = GridSearchCV(ridge, param_grid, cv = kf)
ridge_cv.fit(X_train_scaled, y_train)

print(ridge_cv.best_params_, ridge_cv.best_score_)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

kf = KFold(n_splits= 5, shuffle= True, random_state = 241)

param_grid = {'alpha': np.arange(0.0001, 1, 10),
              'solver': ['sag', 'lsqr']}

ridge = Ridge()
ridge_cv = RandomizedSearchCV(ridge, param_grid, cv = kf, n_iter= 2)
ridge_cv.fit(X_train_scaled, y_train)
print(ridge_cv.best_params_, ridge_cv.best_score_)

In [ ]:
test_score = ridge_cv.score(X_test_scaled, y_test)
test_score

In [ ]:
#Â Set up the parameter grid
param_grid = {"alpha": np.linspace(0.00001, 1, 20)}

# Instantiate lasso_cv
lasso_cv = GridSearchCV(lasso, param_grid, cv=kf)

# Fit to the training data
lasso_cv.fit(X_train_scaled, y_train)
print("Tuned lasso parameters: {}".format(lasso_cv.best_params_))
print("Tuned lasso score: {}".format(lasso_cv.best_score_))

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(np.mean(X), np.std(X))
print(np.mean(X_train_scaled), np.std(X_train_scaled))

In [ ]:
reg_scaled = LinearRegression()
reg_scaled.fit(X_train_scaled, y_train)
y_pred = reg_scaled.predict(X_test_scaled)

squared = reg_scaled.score(X_test_scaled, y_test)
squared

In [ ]:
from sklearn.pipeline import Pipeline

steps = [("scaler", StandardScaler()),
         ("lasso", Lasso(alpha=0.001))]

pipeline = Pipeline(steps)
pipeline.fit(X_train, y_train)

#Â Calculate and print R-squared
print(pipeline.score(X_test, y_test))

In [ ]:
tss = TimeSeriesSplit()

for train_index, test_index in tss.split(X):
    X_train, X_test = X.iloc[train_index, :], X.iloc[test_index,:]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {"Linear Regression": LinearRegression(), "Ridge": Ridge(alpha=0.001), "Lasso": Lasso(alpha=0.001)}
results = []

# Loop through the models' values
for model in models.values():
  kf = KFold(n_splits=6, random_state=42, shuffle=True)
  
  # Perform cross-validation
  cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=kf)
  
  # Append the results
  results.append(cv_scores)

# Create a box plot of the results
plt.boxplot(results, labels=models.keys())
plt.show()

In [ ]:

reg = LinearRegression()

reg.fit(X_train, y_train)
y_predictions = reg.predict(X_test)

# Calculate R-squared, default metric for linear regression, value between 0 and 1
r_squared = reg.score(X_test, y_test)

print(f'R squared: {r_squared}')

# Root Mean squared error, measured in units of target variable squared.
rmse = root_mean_squared_error(y_test, y_predictions)

print(f'RMSE: {rmse}')

In [ ]:
print("Predictions: {},\nActual Values: {}".format(y_predictions[:5], y_test[:5]))

In [ ]:
y_predictions

In [ ]:
plt.plot(y_predictions)

In [ ]:
y_train.resample('ME').mean().plot(label = 'train')
y_test.resample('ME').mean().plot(label = 'test')
y_predictions.value.plot(label = 'predictions')
plt.legend()
plt.show()

In [ ]:
kf = KFold(n_splits= 6)
reg = LinearRegression()
cv_results = cross_val_score(reg, X, y, cv = kf)
print(cv_results)
print(f'The mean score is {np.mean(cv_results).round(3)}, with standard deviation of {np.std(cv_results).round(3)}, {np.quantile(cv_results, [0.025, 0.975])}')

In [ ]:
for name, model in models.items():
  
    # Fit the model to the training data
    model.fit(X_train_scaled, y_train)
  
    # Make predictions on the test set
    y_predictions = model.predict(X_test_scaled)
  
    # Calculate the test_rmse
    test_rmse = root_mean_squared_error(y_test, y_predictions)
    print("{} Test Set RMSE: {}".format(name, test_rmse))

    test_r2 = model.score(X_test_scaled, y_test)
    print("{} R_squared:{}".format(name, test_r2))

In [ ]:
from sklearn.tree import DecisionTreeRegressor

regr_1 = DecisionTreeRegressor(max_depth = 2)
regr_2 = DecisionTreeRegressor(max_depth = 10)

regr_1.fit(X_train_scaled, y_train)
regr_2.fit(X_train, y_train)

y_1 = regr_1.predict(X_test_scaled)
y_2 = regr_2.predict(X_test_scaled)


r_squared = regr_1.score(X_test_scaled, y_test)
r_squared

In [ ]:
r_squared = regr_2.score(X_test_scaled, y_test)
r_squared

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

reg = LinearRegression()

reg.fit(X_train_scaled, y_train)

y_predictions = reg.predict(X_test_scaled)


r_squared = reg.score(X_test_scaled, y_test)

print(f'R squared: {r_squared}')

# Root Mean squared error, measured in units of target variable squared. 
rmse = root_mean_squared_error(y_test, y_predictions)

print(f'RMSE: {rmse}')

In [ ]:
reg = LinearRegression()

reg.fit(X_train, y_train)

y_predictions = reg.predict(X_test)

r_squared = reg.score(X_test, y_test)

print(f'R squared: {r_squared}')

# Root Mean squared error, measured in units of target variable squared. 
rmse = root_mean_squared_error(y_test, y_predictions)

print(f'RMSE: {rmse}')